# 生成 TabBar 图标
# 运行方式: 右键 -> 使用 PowerShell 运行

$iconsDir = Join-Path $PSScriptRoot "assets\icons"

# 确保目录存在
if (-not (Test-Path $iconsDir)) {
    New-Item -ItemType Directory -Path $iconsDir -Force | Out-Null
}

# Base64 图标数据
$icons = @{
    "home.png" = "iVBORw0KGgoAAAANSUhEUgAAAFEAAABRCAYAAACqj0o2AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABjSURBVHhe7dAxDQAgDMSw/3d6gJIO4IKsyJqR/gcAAAAAAAAAAACg/x6R2O/7m9gP+/0oImLfiEjdJRJ1l0jUXSJRd4lE3SUSdZdI1F0iUXeJRN0lEnWXSNRdIlF3iUTdJRJ1l0jUXSJRd4lE3SUSdZdI1F3+AQAAAAAAAAAAAPgPW4kV/4xZq3IAAAAASUVORK5CYII="
    "home-active.png" = "iVBORw0KGgoAAAANSUhEUgAAAFEAAABRCAYAAACqj0o2AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABjSURBVHhe7dAxDQAgDMSw/3d6gJIO4IKsyJqR/gcAAAAAAAAAAACg/x6R2O/7m9gP+/0oImLfiEjdJRJ1l0jUXSJRd4lE3SUSdZdI1F0iUXeJRN0lEnWXSNRdIlF3iUTdJRJ1l0jUXSJRd4lE3SUSdZdI1F3+AQAAAAAAAAAAAPgPW4kV/4xZq3IAAAAASUVORK5CYII="
    "clubs.png" = "iVBORw0KGgoAAAANSUhEUgAAAFEAAABRCAYAAACqj0o2AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABjSURBVHhe7dAxDQAgDMSw/3d6gJIO4IKsyJqR/gcAAAAAAAAAAACg/x6R2O/7m9gP+/0oImLfiEjdJRJ1l0jUXSJRd4lE3SUSdZdI1F0iUXeJRN0lEnWXSNRdIlF3iUTdJRJ1l0jUXSJRd4lE3SUSdZdI1F3+AQAAAAAAAAAAAPgPW4kV/4xZq3IAAAAASUVORK5CYII="
    "clubs-active.png" = "iVBORw0KGgoAAAANSUhEUgAAAFEAAABRCAYAAACqj0o2AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABjSURBVHhe7dAxDQAgDMSw/3d6gJIO4IKsyJqR/gcAAAAAAAAAAACg/x6R2O/7m9gP+/0oImLfiEjdJRJ1l0jUXSJRd4lE3SUSdZdI1F0iUXeJRN0lEnWXSNRdIlF3iUTdJRJ1l0jUXSJRd4lE3SUSdZdI1F3+AQAAAAAAAAAAAPgPW4kV/4xZq3IAAAAASUVORK5CYII="
    "grades.png" = "iVBORw0KGgoAAAANSUhEUgAAAFEAAABRCAYAAACqj0o2AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABjSURBVHhe7dAxDQAgDMSw/3d6gJIO4IKsyJqR/gcAAAAAAAAAAACg/x6R2O/7m9gP+/0oImLfiEjdJRJ1l0jUXSJRd4lE3SUSdZdI1F0iUXeJRN0lEnWXSNRdIlF3iUTdJRJ1l0jUXSJRd4lE3SUSdZdI1F3+AQAAAAAAAAAAAPgPW4kV/4xZq3IAAAAASUVORK5CYII="
    "grades-active.png" = "iVBORw0KGgoAAAANSUhEUgAAAFEAAABRCAYAAACqj0o2AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABjSURBVHhe7dAxDQAgDMSw/3d6gJIO4IKsyJqR/gcAAAAAAAAAAACg/x6R2O/7m9gP+/0oImLfiEjdJRJ1l0jUXSJRd4lE3SUSdZdI1F0iUXeJRN0lEnWXSNRdIlF3iUTdJRJ1l0jUXSJRd4lE3SUSdZdI1F3+AQAAAAAAAAAAAPgPW4kV/4xZq3IAAAAASUVORK5CYII="
    "messages.png" = "iVBORw0KGgoAAAANSUhEUgAAAFEAAABRCAYAAACqj0o2AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABjSURBVHhe7dAxDQAgDMSw/3d6gJIO4IKsyJqR/gcAAAAAAAAAAACg/x6R2O/7m9gP+/0oImLfiEjdJRJ1l0jUXSJRd4lE3SUSdZdI1F0iUXeJRN0lEnWXSNRdIlF3iUTdJRJ1l0jUXSJRd4lE3SUSdZdI1F3+AQAAAAAAAAAAAPgPW4kV/4xZq3IAAAAASUVORK5CYII="
    "messages-active.png" = "iVBORw0KGgoAAAANSUhEUgAAAFEAAABRCAYAAACqj0o2AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABjSURBVHhe7dAxDQAgDMSw/3d6gJIO4IKsyJqR/gcAAAAAAAAAAACg/x6R2O/7m9gP+/0oImLfiEjdJRJ1l0jUXSJRd4lE3SUSdZdI1F0iUXeJRN0lEnWXSNRdIlF3iUTdJRJ1l0jUXSJRd4lE3SUSdZdI1F3+AQAAAAAAAAAAAPgPW4kV/4xZq3IAAAAASUVORK5CYII="
    "profile.png" = "iVBORw0KGgoAAAANSUhEUgAAAFEAAABRCAYAAACqj0o2AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABjSURBVHhe7dAxDQAgDMSw/3d6gJIO4IKsyJqR/gcAAAAAAAAAAACg/x6R2O/7m9gP+/0oImLfiEjdJRJ1l0jUXSJRd4lE3SUSdZdI1F0iUXeJRN0lEnWXSNRdIlF3iUTdJRJ1l0jUXSJRd4lE3SUSdZdI1F3+AQAAAAAAAAAAAPgPW4kV/4xZq3IAAAAASUVORK5CYII="
    "profile-active.png" = "iVBORw0KGgoAAAANSUhEUgAAAFEAAABRCAYAAACqj0o2AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABjSURBVHhe7dAxDQAgDMSw/3d6gJIO4IKsyJqR/gcAAAAAAAAAAACg/x6R2O/7m9gP+/0oImLfiEjdJRJ1l0jUXSJRd4lE3SUSdZdI1F0iUXeJRN0lEnWXSNRdIlF3iUTdJRJ1l0jUXSJRd4lE3SUSdZdI1F3+AQAAAAAAAAAAAPgPW4kV/4xZq3IAAAAASUVORK5CYII="
}

# 生成图标文件
foreach ($name in $icons.Keys) {
    $filepath = Join-Path $iconsDir $name
    $bytes = [Convert]::FromBase64String($icons[$name])
    [System.IO.File]::WriteAllBytes($filepath, $bytes)
    Write-Host "Created: $name" -ForegroundColor Green
}

Write-Host "`n✅ All icons generated successfully!" -ForegroundColor Cyan
Write-Host "Refresh your WeChat DevTools to see the icons."
